### ISSUE TITLE
blank checkout success page

### ISSUE THREAD

**Issue by gribos** [loadedcommerce/loaded7#522]
Hi,
I found a issue with checkout success page. When you buying something in shop, the last page in checkout process (page after confirmation of purchase) is blank.

the reason is that You have a bug in  \templates\core\content\checkout\checkout_success.php

LINE 114:
foreach (lC_Success::getOrderTotals($oID) as $module as $module) { 

it should be : 
foreach (lC_Success::getOrderTotals($oID) as $module) {

**Comment by saliozzia** [comment]
does this occur when no modules are loaded?

**Comment by ChadReitsma** [comment]
Honest mistake in the code, easy fix though! Thnx gribos!!

**Comment by datazen** [comment]
This issue is resolved.
