### ISSUE TITLE
new products content module breaks cache [$5]

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/loaded7#523]
turning on the new products module causes the cache to break resulting in a blank page on the home page.

**Comment by ChadReitsma** [comment]
I just commented out the $lC_Cache->write($data); line and that works - it's not a fix, but it works in a pinch - lookin' forward to the next milestone! :)

File: \includes\content\modules\new_products.php
Line: 66

**Comment by saliozzia** [comment]
can you please edit the develop branch or do a pull request with the code fix?

**Comment by saliozzia** [comment]
also you can do it through buontysource and get the bounty. we may use that process more if people like it.

**Comment by wa4u** [comment]
Fixed and tested on a site. Testing on another site with similar issue. After confirmation will commit the fix.

**Comment by datazen** [comment]
Repaired cache issue and also repaired issue with Buy Now not adding to cart.  Committed to develop branch and will be out in next release.
