### ISSUE TITLE
Export / Import manufacturer data missing

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/loaded7#526]
data for manufacturer is missing from export and import

![screenshot](http://i.grab.la/05210-1dc4b904-2956-40b9-983d-adb575e22ca9.png)

**Comment by saliozzia** [comment]
also fixed SKU data handling. was an issue with null data support.

**Comment by datazen** [comment]
Updated develop branch with the fix. This will be picked up in the next release.
