### ISSUE TITLE
Margin Reports

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/loaded7#527]
Here is the Margin Report
Here is a screenshot bring up the Margin Report, please not this is a test site with B2B
http://grabilla.com/05213-28dbc7cf-188a-4cf5-aa80-b384d482589d.png

This may not be a completed report for Pro, but should say something to let people know this feature is still being developed at this time.

**Comment by datazen** [comment]
Added code to hide the upsell if using Pro or B2B until the report is actually done.
