### ISSUE TITLE
Admin Right Navigation Menu Loses Position

### ISSUE THREAD

**Issue by tekyguy** [loadedcommerce/loaded7#531]
If I go in to Zones and click Ohio, the right nav menu goes all the way back out: http://grab.by/F0Qg

**Comment by datazen** [comment]
Could not duplicate.  This does not appear to be an issue.

http://grabilla.com/05401-24f325f5-e96a-4936-a76f-805d8e88aa4a.html#

**Comment by tekyguy** [comment]
https://rccrazed.com/admin/index.php?zone_groups=1  is the URL where the menu loses it's place.  Thanks!
