### ISSUE TITLE
information page permalinks missing data, wont save

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/loaded7#534]
When SEO URLS are turned on, the information page in the information category do not link
 
Due to 
A. the category page type "information category" not supporting a permalink, all children pages of a inforamtion category will fail to save their 
B.  An additional error is encountered by the presence of a special char in the preinstalled data for shipping & returns and for terms & condition pages

solution:

1. update /admin/index.php?categories to allow for saving permalinks like normal categories
and 
2. Add the following to the install SQL
(40, 3, 1, 1, 'cPath=2_3', 'shipping-returns'),
(42, 4, 1, 1, 'cPath=2_4', 'privacy-policy'),
(43, 2, 1, 1, 'cPath=2', 'information'),
(44, 5, 1, 1, 'cPath=2_5', 'terms-conditions');

**Comment by datazen** [comment]
Could not duplicate save issue.  Tried adding new and entered data into every field. Also tried with special chars and all saves good.

http://grabilla.com/05402-b7c47dc3-3989-450e-823a-6981bf3d043a.html#

Updated install SQL with default SEO values for info pages.
