### ISSUE TITLE
product permalink for multilanguage sites - breaks on product page when language changes

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/loaded7#536]
when a product has differnt permalinks for english, spanish, etc

and the catalog user is on the page in a specific language, and changes the language, the product is lost, and redirected to product.php with no value.

solution:

ignore the language when loading the page via a permalink. only use language for building links in the infoboxes and listing, but allow any mix of permalink and language combo when finding the product from a URL parse event.

**Comment by wa4u** [comment]
Duplicate: https://github.com/loadedcommerce/loaded7/issues/566
