### ISSUE TITLE
Product / category Create / Update issue

### ISSUE THREAD

**Issue by mattloaded** [loadedcommerce/loaded7#542]
Customer cannot create new products / categories, cannot update the existing category or product. After filling all the details on product edit/create page, after click on save / save close it simply loads the product / category listing page, but doesnt save/create the new / existing product data.

**Comment by mattloaded** [comment]
Fix : Investigated the issue and found that the issue was with default values on lc_products/lc_categories columns. Many columns doesn't have default value set due to which it throws error, 
http://grabilla.com/05318-2bba6406-5572-4d12-b7fc-a67d28c65dca.html#

ALTER TABLE  `lc_products` CHANGE  `parent_id`  `parent_id` INT( 11 ) NOT NULL DEFAULT  '0',
CHANGE  `products_quantity`  `products_quantity` INT( 11 ) NOT NULL DEFAULT  '0',
CHANGE  `products_weight_class`  `products_weight_class` INT( 11 ) NOT NULL DEFAULT  '0',
CHANGE  `products_status`  `products_status` TINYINT( 1 ) NOT NULL DEFAULT  '0',
CHANGE  `products_tax_class_id`  `products_tax_class_id` INT( 11 ) NOT NULL DEFAULT  '0',
CHANGE  `products_ordered`  `products_ordered` INT( 11 ) NOT NULL DEFAULT  '0',
CHANGE  `is_subproduct`  `is_subproduct` TINYINT( 1 ) NOT NULL DEFAULT  '0',
CHANGE  `access_levels`  `access_levels` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT  '1;2',
CHANGE  `groups_pricing_enable`  `groups_pricing_enable` TINYINT( 1 ) NOT NULL DEFAULT  '0',
CHANGE  `qpb_pricing_enable`  `qpb_pricing_enable` TINYINT( 1 ) NOT NULL DEFAULT  '0',
CHANGE  `specials_pricing_enable`  `specials_pricing_enable` TINYINT( 1 ) NOT NULL DEFAULT  '0'

Fix tested on 3 clients and got confirmation, it worked fine.

**Comment by datazen** [comment]
Both install.sql and core update runAfter have already been updated with the proper default values.  You can fix this issue on an older site by uploading the latest version and clicking the DB Update button on the Core Update page.
