### ISSUE TITLE
Admin becomes unresponsive after editing a template modules layout content

### ISSUE THREAD

**Issue by tekyguy** [loadedcommerce/loaded7#545]
From here: https://rccrazed.com/admin/index.php?templates_modules_layout&set=content  

I edit one, then click cancel, the admin is completely unresponsive and I must reload the URL to continue.

**Comment by datazen** [comment]
Repaired menu marker for zone groups

**Comment by geraldbullard** [comment]
IN Firefox, @ v7.003.3.3 Pro I do not see this issue. Can you post the Browser/Version you were using to reproduce this error? Thanks!

**Comment by saliozzia** [comment]
this was a chrome issue and is resolved in the latest version of chrome.

closing this as resovled.
