### ISSUE TITLE
Customers who bought this product also purchased price issue

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/loaded7#550]
"Customers who bought this product also purchased" module prices are same as price displayed on product info page. http://prntscr.com/6qvxtf

Solution: includes/modules/content/also_purchased_products.php
Add below code after line # 61
$lC_Product = new lC_Product($Qorders->value('products_id'));

**Comment by wa4u** [comment]
Committed fix to B550

**Comment by wa4u** [comment]
Fixed: https://github.com/loadedcommerce/loaded7/commit/1f78a0c15027fae2f11bbe6fd1df9524072a3560

![also-purchased-bug](https://cloud.githubusercontent.com/assets/3207057/7324696/3e3a8d70-ead6-11e4-8ec5-968b3ed7364a.png)

**Comment by saliozzia** [comment]
fixed by #1f78a0c

**Comment by geraldbullard** [comment]
Merged into develop.
