### ISSUE TITLE
need to disable/enable cache  - disabled by default

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/loaded7#553]
the cache technology causes lots of issues as various modules and admin pages do not either clear, update or read from the cache correctly.

most stores do not have so much traffic that the cache is beneficial.

we need the cache to be disabled initially and only enabled when a store owner needs it for performance.

**Comment by saliozzia** [comment]
This has been done in 7.003.3.2

However after core updating i am unable to locate the setting to enable or disable.

**Comment by datazen** [comment]
Its a Service.  Go to Setup > Modules > Services

**Comment by wa4u** [comment]
setCache() function in template.php and language.php create issues like hiding home page modules and not loading proper language definitions.

**Comment by saliozzia** [comment]
kiran, 

Are you describing an issue that exist after the 7.003.3.3 update with the cache fix?

**Comment by wa4u** [comment]
Yes. Hiding home page modules and showing language defines were fixed by commenting setCache() lines in template class and language class.

**Comment by geraldbullard** [comment]
The original scope of this issue was to have cache disabled by default, which has been done in 7.003.3.3. Kiran's issue looks to be related directly to issue #551 https://github.com/loadedcommerce/loaded7/issues/551. Closing.
