### ISSUE TITLE
Email from customer orders issue

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/loaded7#554]
Received test order from email

here is the format iw as recieved in

Magnum Web Design
email_order_separator
email_order_order_number
email_order_invoice_url
email_order_date_ordered

email_order_products
email_order_separator
1 x Make A Payment () = $10.00
email_order_separator
Sub-Total: $10.00
Free Shipping (for orders over $0.00): $0.00
Total: $10.00

email_order_delivery_address
email_order_separator
Jim McGettigan
135 Armistice Blvd
Pawtucket RI 02860
United States of America

email_order_billing_address
email_order_separator
Jim McGettigan
135 Armistice Blvd
Pawtucket RI 02860
United States of America

email_order_status
email_order_separator
email_order_payment_method
email_order_separator
PayPal Payments Standard

**Comment by saliozzia** [comment]
reinstall the languge pack and place another order. was this on an update or a fresh install?

**Comment by geraldbullard** [comment]
Awaiting reply from Jim. Ping.
