### ISSUE TITLE
after Upgrade to 7.003.3.1 Server error

### ISSUE THREAD

**Issue by tnt4ever** [loadedcommerce/loaded7#556]
hi,

i have upgraded my CRE B2B pro from 7.002.6.0 to 7.003.3.1 now on website http 500 error & /admin is blank.

how to fix it.

**Comment by saliozzia** [comment]
Please contact our support staff at our website. Git hub is for code work.

**Comment by tnt4ever** [comment]
thank you. i managed to delete the addon COD & it working for few minutes. iput my key & now admin show visitors & top bar only. any suggestion ?

**Comment by saliozzia** [comment]
Did you contact support?
