### ISSUE TITLE
Debug code in add_cart.php

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/loaded7#558]
Scott,

There is debug code has come by mistake in includes/modules/actions/add_cart.php which stops script from execution and shows debug data.

line # 58 to 61

echo "<pre>";
print_r($_POST);
echo "</pre>";
die('77');

**Comment by wa4u** [comment]
Removed unwanted code and committed.

**Comment by datazen** [comment]
merged into develop and release as hotfix 7.003.3.3
