### ISSUE TITLE
Wrong file path in update script

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/loaded7#559]
Wrong file path in updates application.
File: admin/includes/applications/updates/classes/updates.php
Line# 780

exec(CFG_APP_ZIP . ' -r ' . DIR_FS_WORK . 'updates/' . $backup_file . ' ' . DIR_FS_CATALOG . '* -x "/home/loadedne/www/sandbox/datazen/www/loaded7/catalog/images/products/*" -x "*.cache" -x "*.zip" -x "php_error*" -x "*.gif" -x "*.jpg" -x "*.jpeg" -x "*.png" -x "*.sql" -x "*.tgz" -x "*.tar" -x "*.gz"');

**Comment by wa4u** [comment]
Fixed and committed.

**Comment by datazen** [comment]
merged into develop and release as hotfix 7.003.3.3
