### ISSUE TITLE
Clicking add to cart does not add product to cart

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/loaded7#562]
Clicking add to cart does not add product to cart. The product information page reloads and no product gets added to cart.

The url contents are something like this;
http://www.domain.com/products.php?test-product-1&amp;action=cart_add&amp;info=1&amp;lCsid=oc4mo4hpa117shasrl0j4fbii4

& turns to & amp;

If we comment includes/functions/html_output.php
 line# 197
$link = str_replace('&', '& amp;', $link);

Add to cart works fine.

**Comment by geraldbullard** [comment]
I added a fix for this just recently to the develop branch:

https://github.com/loadedcommerce/loaded7/commit/0976611b978fe69ab432b4607d828a84459a9f0f

**Comment by geraldbullard** [comment]
Closing Issue, fixed in develop branch.
