### ISSUE TITLE
Uppercase image file name extensions does not work.

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/loaded7#567]
Some site admins use uppercase image file extensions, which result in broken image. Allowing uppercase image filename extension in validations will solve the issue.

**Comment by wa4u** [comment]
Fixed and committed.

**Comment by geraldbullard** [comment]
Ty Kiran, just by chance did you check if a strtolower might have done the same thing, if it was possible to do with only one addition, and not all throughout the code base? Just a thought?

**Comment by geraldbullard** [comment]
Merged into develop, closing.
