### ISSUE TITLE
Product option values not saving 

### ISSUE THREAD

**Issue by mattloaded** [loadedcommerce/loaded7#573]
Product option not saving while updating the product. 
Steps to reproduce the issue : 
1. Login to the cart admin >> catalog >> product list >> edit the product >> select option tab.
2. In the option tab, select the option, and select next to tick the option values. 
3. Once option selected, save the product. 
After saving the product try to edit the product again. The product option is saved but the option values for the products donot get saved. 
Due the option values not saved, the product option doesn't get showed  at a caatlog end.

**Comment by geraldbullard** [comment]
My first testing on 7.003.3.3 Pro install sandbox does not have any issues I can detect saving, editing, removing, and re-adding options. I will get with Matt tomorrow and see about updating Dungeons site to latest Pro and re-testing.

**Comment by geraldbullard** [comment]
This is another issue related to the recent simple options code work. I do believe this issue to be resolved with a small cde adjustment going into next release for getSimpleOptionsTbody function.
