### ISSUE TITLE
Disable add to cart for Sub Products

### ISSUE THREAD

**Issue by geraldbullard** [loadedcommerce/loaded7#577]
Per Support Ticket [ SMF-761-67833 ]:
 
How to reproduce issue:

1) Configure Stock in Admin See Values -> http://grabilla.com/05408-0699257c-2a3b-4a42-bb68-41d693059a61.html

    a) Check Stock Level = YES
    b) Subtract Stock = YES
    c) Autodisable out of stock product = YES
    d) Disable Add to Cart for out of stock products = YES
    e) Mark product out of stock = ***
    f) Stock Re-order level = 5

2) Add a new product
3) Add a couple of sub-products
4) Add quantity of 1 for each one
5) (This step is a pain in the @$$, but it I guess it “works”?)
a. Click on the “Data” tab of the product
b. Then Click on the “Single SKU”
c. Change Qty On Hand to a number greater than 0 (this allows the sub-products to be able to be ordered)
6) Log into the catalog
7) Go to the product
8) Add qty of 1 of one of the sub-products to you cart ( since there is only 1 in stock, you should be creating an out of stock case)
9) Check out.
10) Go back to the product in the catalog, and verify it is gone.
11) Log into the admin (or simply refresh the page to get up-to-date data on the product)
12) Go to Options Tab
13) Make sure Multi SKU is selected
14) Verify that the QOH is 0 for the product you just ordered All is
good… EXCEPT!
15) http://grabilla.com/05409-93ae6c92-538a-44d5-a8f9-bed9920b0dc5.html
The Database has the products_status =0 , but the status on the screen
still has a checkbox…. ( not really a huge deal, as this is only viewed at
this point, but if you were to click “Save”, it would change the status on
this field)

**Comment by geraldbullard** [comment]
Core and Pro have been updated for this issue. The Sub Products listing in Admin (Pro) now reflects the correct sub products status, and the store side (Core) now disables the add to cart button and qty input field for sub products if Disable Add to Cart is True, further the Sub Products will be hidden if the "Autodisable out of stock product" is true and the subs quantity is below 1

**Comment by saliozzia** [comment]
If there are 10 sub products and 9 of them have a stock greater then 0 but
one has 0 or less. We should still show the parent and the 9 other subs
that have available stock.

On Tuesday, May 12, 2015, Gerald Bullard Jr <notifications@github.com>
wrote:

> Closed #577 <https://github.com/loadedcommerce/loaded7/issues/577>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loadedcommerce/loaded7/issues/577#event-302253878>.
>


-- 
-Sal

Sent from Gmail Mobile

**Comment by geraldbullard** [comment]
Yes that is exactly what the fix is for.
