### ISSUE TITLE
HTML error

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/loaded7#583]
catalog/includes/modules/product_listing.php

line# 64 
$output .= '<div class="product-listing-module-manufacturer' . lc_link_object(lc_href_link(FILENAME_DEFAULT, 'manufacturers

missing "> after product-listing-module-manufacturer

**Comment by wa4u** [comment]
Fixed and committed.

**Comment by geraldbullard** [comment]
merged into develop
