### ISSUE TITLE
Loaded 7 Upgrader - Product Sort Data

### ISSUE THREAD

**Issue by tekyguy** [loadedcommerce/loaded7#588]
The product sort data from 6.X need to be carried forward into Loaded 7 by the upgrade so that customers don't need to re-sort all of their products after upgrade.

**Comment by datazen** [comment]
I have already committed this to our core.  It will be out in the next release.

 

-Scott

**Comment by tekyguy** [comment]
Understood but does that also include the upgraded functionality also?



Richard Stupansky Jr
President
The Reactor Works, Inc.
+1 (216) 233 5154
Skype: tekyguy

**Comment by geraldbullard** [comment]
I have added the products sort order to come over in upgrade, having Kiran Test to confirm.

**Comment by geraldbullard** [comment]
merged into develop, closing.
