### ISSUE TITLE
After Core Update - Admin products not loading 

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/loaded7#602]
Running Core Update from 7.003.3.3 to 7.00.3.4.0 

Clicking products menu option, the products page do not load. 

Screenshot
![Screenshot](http://grabilla.com/0560f-4985aaaa-48a4-4a43-bb99-88441c917876.png)

Expected results is product to load.

**Comment by geraldbullard** [comment]
After my core update from 7.003.3.3 to 7.003.4.0 I do not have this issue. can you confirm on second site?

**Comment by jimmcget** [comment]
ON fresh install I did not have this issue, however when I cleared cache manually, the issue was resolved.
