### ISSUE TITLE
After upgrade products show as blank and no price or pic

### ISSUE THREAD

**Issue by pittsoy315** [loadedcommerce/loaded7#603]
After upgrading to latest version the products still are showing correctly and active in admin but on frontend they show with price as $0.00 and no pic or options of any kind almost like a blank product with just name of product

**Comment by geraldbullard** [comment]
Is this a Core, a Pro or a B2B installation?

**Comment by pittsoy315** [comment]
Its Core, I received notification today when I logged on to admin that a new version was available

**Comment by geraldbullard** [comment]
Have you tried the rollback feature? If so does it resolve the issue?

**Comment by pittsoy315** [comment]
I ended up just rolling back and it did resolve the issue

**Comment by jimmcget** [comment]
I did find by removing cache manually, the products did show again.

**Comment by datazen** [comment]
I assume you using Core Updater?

**Comment by pittsoy315** [comment]
yes
