### ISSUE TITLE
Discount coupon when applied adds discount amount 

### ISSUE THREAD

**Issue by mattloaded** [loadedcommerce/loaded7#611]
Discount coupon when added to the cart, adds the discount amount instead of deducting it from order total. The order total shown on checkout shipping and checkout payment/confirmation page shows order_total + discount price. 
Steps to reproduce : 
1. Create a coupon in cart admin 
2. Purchase one product and proceed to checkout. 
3. On shipping checkout page,apply the coupon. 
4. On the left hand side the order total will show order total + coupon charges. 
5. same total will be shown on all remaining checkout pages.

**Comment by mattloaded** [comment]
Updated the below code in checkout_payment.php and checkout_shipping.php file located at, 

templates\core\content\checkout

at line : 69, 

commented //if ($module['code'] != 'total') $total = $total + (float)$module['value'];
 and just below it added, 

                    if (($module['code'] != 'total') && ($module['code'] != 'coupon')) $total = $total + (float)$module['value'];
		    if ($module['code'] == 'coupon') $total = $total - (float)$module['value'];

**Comment by geraldbullard** [comment]
Added to develop branch. Closing.
