### ISSUE TITLE
Loaded 7 CORE Update - 7.003.4.0 Products disappear from catalog

### ISSUE THREAD

**Issue by tekyguy** [loadedcommerce/loaded7#622]
I updated to 7.003.4.0 and my catalog lost the product I had there.  I have heard Jim say he had the same problem so I am creating this issue.

Catalog:  http://grab.by/IoCg

Admin: http://grab.by/IoCk

**Comment by tekyguy** [comment]
I also cannot edit any existing product, the changes are not saved.

**Comment by jimmcget** [comment]
I cannot add new products either

**Comment by tekyguy** [comment]
I cannot add new products as well.

**Comment by geraldbullard** [comment]
I see that the cart was running Pro. Was this an issue in Core?

**Comment by tekyguy** [comment]
I don't know. But it lost pro and the products. Adding the pro serial didn't fix the products if you see what I mean. 



Richard Stupansky Jr
President
The Reactor Works, Inc.
+1 (216) 233 5154
Skype: tekyguy

**Comment by geraldbullard** [comment]
I found the issue for the disappearing products, the runafter controller for the 7.003.4.0 needs an added products table additional column that is missing causing sql error. updating in develop.

**Comment by geraldbullard** [comment]
This may not account for the loss of Pro, that is most likely another issue.

**Comment by geraldbullard** [comment]
Fixed in develop branch.

**Comment by geraldbullard** [comment]
Addressing save issues further.

**Comment by geraldbullard** [comment]
Save issue is most likely fixed as well with updated products table additional column "products_sort_order". Closing Issue.
