### ISSUE TITLE
PayPal Payment Issue - Transferring state name to PayPal, not State Abbreviation as required

### ISSUE THREAD

**Issue by tekyguy** [loadedcommerce/loaded7#623]
See this screenshot: http://grab.by/IoIE  

Our cart is transmitting the state name as highlighted in RED, PayPal requires the State Abbreviation.

**Comment by geraldbullard** [comment]
Matt please look into this issue. Thanks.

**Comment by tekyguy** [comment]
This is with PayPal Standard add on, just FYI.

**Comment by tekyguy** [comment]
This is fixed.
