### ISSUE TITLE
PayPal Standard Issue - Item Number data can contain special chars, breaks IPN

### ISSUE THREAD

**Issue by tekyguy** [loadedcommerce/loaded7#631]
Currently the module is sending product names in the item number field, shouldn't this be product ID?  This breaks IPN.  See the attached image with item_number example in it.
![screen shot 2015-07-02 at 12 44 16 pm](https://cloud.githubusercontent.com/assets/3209614/8482523/24c6867e-20b8-11e5-8159-d51f9877e383.png)

**Comment by geraldbullard** [comment]
Updated the item_number to send the "item_id" as in the Itemized switch. Will await more orders via paypal to determine if fix is successful.

**Comment by tekyguy** [comment]
Attached is a screenshot of what the result is, I can test this without real orders...just don't complete the paypal payment ;-)  YOu can see that now we are sending 1, 2, 3 for the three products but it should be the database product_id.  You can also see here the state error.  Looks like we are still sending the full state name.
![screen shot 2015-07-06 at 1 03 00 pm](https://cloud.githubusercontent.com/assets/3209614/8528725/f6a71938-23e2-11e5-905f-7078abdf72e8.png)

**Comment by tekyguy** [comment]
Now product ID is sending, I think this issue is resolved.  IPN is still not working and I have opened another issue for that.
