### ISSUE TITLE
PayPal Standard Issue - IPN fails on multiple customer sites

### ISSUE THREAD

**Issue by tekyguy** [loadedcommerce/loaded7#642]
Kiran already working and has all the details.  Creating the issue for tracking.

**Comment by datazen** [comment]
Issue resolved.  Added logic to update permissions on ipn.php file to 755 upon module install

**Comment by datazen** [comment]
Order Status staying at 0

**Comment by tekyguy** [comment]
This was resolved with Devi's latest fix.  Devi please ensure you submit the code.
