### ISSUE TITLE
addons download full catalog (7.003.4.2)

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/loaded7#683]
When we install addon (shipping, payment, language, etc) from addons entire catalog is downloaded in addons/<addon_folder>/ 
language installation too downloaded full catalog in addons folder.

![addons](https://cloud.githubusercontent.com/assets/3207057/9607200/7b3a8638-50e5-11e5-822b-c979819b8488.png)

**Comment by datazen** [comment]
fixed and closed
